const teamLogos = { 
  "Arsenal": "https://resources.premierleague.com/premierleague25/badges/3.svg", 
  "Aston Villa": "https://resources.premierleague.com/premierleague25/badges/7.svg", 
  "Bournemouth": "https://resources.premierleague.com/premierleague25/badges/91.svg", 
  "Brentford": "https://resources.premierleague.com/premierleague25/badges/94.svg", 
  "Brighton": "https://resources.premierleague.com/premierleague25/badges/36.svg", 
  "Chelsea": "https://resources.premierleague.com/premierleague25/badges/8.svg", 
  "Coventry City": "https://resources.premierleague.com/premierleague25/badges/9.svg",
   "Crystal Palace": "https://resources.premierleague.com/premierleague25/badges/31.svg",
    "Everton": "https://resources.premierleague.com/premierleague25/badges/11.svg",
     "Fulham": "https://resources.premierleague.com/premierleague25/badges/54.svg",
      "Hull City": "https://resources.premierleague.com/premierleague25/badges/88.svg",
       "Ipswich Town": "https://resources.premierleague.com/premierleague25/badges/40.svg",
        "Leeds": "https://resources.premierleague.com/premierleague25/badges/2.svg", 
        "Liverpool": "https://resources.premierleague.com/premierleague25/badges/14.svg", 
        "Man City": "https://resources.premierleague.com/premierleague25/badges/43.svg", 
        "Man Utd": "https://resources.premierleague.com/premierleague25/badges/1.svg", 
        "Newcastle": "https://resources.premierleague.com/premierleague25/badges/4.svg", 
        "Nott'm Forest": "https://resources.premierleague.com/premierleague25/badges/17.svg", 
        "Spurs": "https://resources.premierleague.com/premierleague25/badges/6.svg",
         "Sunderland": "https://resources.premierleague.com/premierleague25/badges/56.svg" };
export default teamLogos;